### PR TITLE
New HA version compatibility

### PR DESCRIPTION
**Pull request by holowinski**
Hi.

A quick PR updating the python-miio to the new version.
Works for my V3 on newest HA.

### CODE REVIEW

**Comment by amoebapl** [comment]
It helped.
Thanks

**Comment by kkarkos** [comment]
This might fix https://github.com/marotoweb/home-assistant-vacuum-viomise/issues/19

**Comment by istvan-olah** [comment]
@marotoweb this should be deployed as a beta version for now, as it fixes the issue with the Viomi V3

**Comment by marotoweb** [comment]
Currently I don't have any version of HA although I still have this vacuum cleaner working. Can anyone confirm which version of HA this integration is still working on?

**Comment by FliesWithWind** [comment]
It works with the latest version for me.

**Pull request merged**
